### ISSUE TITLE
css: cursor:pointer; empfolen

### ISSUE THREAD

**Issue by LFF5644** [mattes2008/TicTacToe#3]
ich würde an diese zeile code noc `cursor:pointer;`
adden damit wenn man mir der mouse über dem settings div ist das dann kein `cursor: text;` sondern ein `cursor: pointer;` angezeigt wird!
ps. für sachen wie `display:none` eine extra `hidden`classe zu erstellen ist verschwendung von platz!
`style="display:none"` einfach adden!
https://github.com/mattes2008/TicTacToe/blob/ace27df69d6e149bee01cdf5192a23ae2db7a3ed/index.html#L83

**Comment by mattes2008** [comment]
### Gute Idee

Ich habe in das Settings-Heading und das Settings-Div _cursor: pointer;_ eingebaut. Die _hidden_-Klasse muss aber bleiben, da ich sonst alle anderen Css-Attribute der Elemente auch neu einfügen müsste.

**Comment by L3P3** [comment]
Ne, du kannst `element.style.display='block'` nehmen oder `element.style.display='none'`. Das überschreibt die anderen Eigenschaften nicht! Wenn du aber schon Klassen benutzt, solltest du es einheitlich machen und überall Klassen nutzen, also auch das style-Attribut als solches nicht mehr nutzen. Sonst muss man für Style an mehreren Stellen gucken und das ist nervig bei größeren Projekten.

**Comment by L3P3** [comment]
Und wenn du eine Änderung committest, kannst du dieses Issue mit #3 in der Beschreibung referenzieren, dann wird der Commit hier angezeigt und man muss nicht erst danach suchen!

**Comment by LFF5644** [comment]
er ist nicht so dumm wie er aussiht

**Comment by L3P3** [comment]
Ich finde nicht dass er dumm aussieht.
