### ISSUE TITLE
Rework return of checkForWin

### ISSUE THREAD

**Issue by nodi-andy** [mattes2008/TicTacToe#5]
Rework the checkForWin based on following specification:

Input:  9 char string
Output: Return either 
"x" : X has won
"o": Y has won
"invalid": Game state is invalid, includes also the case where both player (x,o) won the game
"active": on going game, no one have one
"remis": All fields are full but not one have one

**Comment by mattes2008** [comment]
I think you opened the wrong file.
Right file: scriptsEdited.js

**Comment by nodi-andy** [comment]
The line 15 of /TicTacToe/blob/master/else/scriptsEdited.js is commented out (//return "invalid") and in some cases the board state is invalid, like: "xxxo-----", because "x" can not be played 3 times
